from . import eran_quotation_loi_wiz
from . import eran_purchase_request_line_make_purchase_order_wiz
from . import eran_stock_picking_return
from . import eran_stock_picking_refund
from . import eran_material_request_wiz
from . import eran_mail_compose_message
from . import eran_label_sto_wiz
from . import stock_invoice_onshipping
from . import eran_global_discount_wiz
from . import eran_mrp_non_material_wizard
from . import eran_mrp_consumption_warning
from . import eran_delivery_schedule_wizard
from . import eran_sale_invoice_advance_wiz
from . import eran_purchase_order_advance_payment_wiz