from . import res_company
from . import eran_purchase
from . import eran_sale
from . import eran_quotation
from . import eran_stock_opname
from . import eran_product_inventory
from . import eran_purchase_request
from . import eran_stock_picking
from . import eran_order_sheet
from . import eran_hr
from . import eran_master_shift
from . import eran_account_payment_term
from . import eran_vendor_pricelist
from . import eran_mrp_forecast_order
from . import eran_workcenter_group
from . import eran_mrp_workcenter
from . import eran_mrp_bom
from . import eran_product_pricelist_item
from . import eran_ng_mrp_production
from . import eran_no_good
from . import eran_quality
from . import eran_stock_picking_batch
from . import eran_account_move
from . import eran_production_report
from . import eran_kpi_vendor_report
from . import eran_production_performance_report
from . import eran_mrp_production
from . import eran_sequence_setting
from . import eran_attendance
# from . import eran_cost_vendor_pricelist
from . import eran_cost_vendor_pricelist
from . import eran_stock_quant
from . import eran_category_group
from . import eran_tag_sto
from . import eran_dashboard_master
from . import eran_sale_request_quotation
from . import eran_pica
from . import eran_account_asset
from . import eran_stock_scarp