{
    'name': 'ERAN Custom',
    'summary': "Custom modul project ERAN",
    'description': """
        v1.0.0
        By: DSN Team
    """,
    'author': "Delta Solusi Nusantara",
    'website': "www.dsnusantara.com",
    'version': '16.0.1.0.0', 
    'data': [
        #security
        'security/ir.model.access.csv',
        'security/eran_scurity_groups.xml',

        #report
        'report/purchase_order_report.xml',
        'report/eran_invoice_report.xml',
        'report/eran_delivery_order_report.xml',
        'report/faktur_pajak_report.xml',
        'report/eran_label_sto_report.xml',
        'report/eran_quotation_report.xml',
        'report/eran_receipt_of_goods_report.xml',
        'report/eran_sj_subcon_report.xml',
        'report/eran_label_qc_report.xml',
        'report/eran_request_material_report.xml',
        'report/eran_label_of_receipt.xml',
        'report/eran_cost_structure_report.xml',
        'report/eran_lembar_masalah_kualitas_report.xml',
        'report/purchase_quotation_templates.xml',
        'report/eran_delivery_schedule_report.xml',
        'report/eran_mrp_production_report.xml',
        'report/eran_forecast_order_report.xml',
        'report/eran_order_sheet_vendor_report.xml',
        'report/eran_report_action.xml',
        'report/eran_report_cla.xml',
        'report/eran_sale_order_report.xml',
        'report/eran_purchase_request_report.xml',
        'report/eran_order_sheet_customer_report.xml',
        'report/eran_account_asset_report.xml',
        'report/eran_tag_sto_report.xml',
        
        #data
        'data/eran_sequence.xml',
        'data/mrp_bom_cron.xml',
        'data/eran_mail_template.xml',
        'data/eran_part_defect_type.xml',
        'data/eran_area_found.xml',
        'data/eran_action_menu.xml',
        'data/eran_rule.xml',
        'data/eran_pica_sequence.xml',
        
        #views
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/eran_quotation_view.xml',
        'views/eran_stock_opname_view.xml',
        'views/eran_product_inventory.xml',
        'views/eran_stock_picking.xml',
        'views/eran_order_sheet_views.xml',
        'views/eran_purchase_request_view.xml',
        'views/eran_hr_views.xml',
        'views/eran_purchase_order_line_views.xml',
        'views/eran_master_shift.xml',
        'views/eran_account_payment_term_view.xml',
        'views/eran_vendor_pricelist_view.xml',
        'views/eran_account_move_view.xml',
        'views/eran_purchase_order_views.xml',
        'views/eran_workcenter_group_view.xml',
        'views/eran_stock_scrap_view.xml',
        'views/eran_mrp_workcenter_view.xml',
        'views/eran_mrp_bom_view.xml',
        'views/eran_mrp_production_view.xml',
        'views/eran_no_good_view.xml',
        'views/eran_quality_view.xml',
        'views/eran_ng_mrp_production_view.xml',
        'views/eran_mrp_forecast_order_views.xml',
        'views/eran_stock_picking_batch_views.xml',
        'views/eran_sale_view.xml',
        'views/eran_production_report_view.xml',
        'views/eran_stock_picking_type_views.xml',
        'views/eran_kpi_vendor_report.xml',
        'views/eran_production_performance_report_view.xml',
        'views/eran_cost_vendor_pricelist_views.xml',
        'views/eran_sequence_setting_views.xml',
        'views/eran_category_group_view.xml',
        'views/eran_tag_sto_view.xml',
        'views/eran_dashboard_master_view.xml',
        'views/eran_sale_request_quotation_view.xml',
        'views/eran_workcenter_activity_view.xml',
        'views/eran_account_asset_view.xml',
        'views/eran_attendance_view.xml',

        #wizard
        'wizard/eran_quotation_loi_wiz_view.xml',
        'wizard/eran_purchase_request_wiz_view.xml',
        'wizard/eran_stock_picking_refund_view.xml',
        'wizard/eran_stock_picking_return_view.xml',
        'wizard/eran_material_request_wiz_view.xml',
        'wizard/eran_label_sto_wiz_view.xml',
        "wizard/eran_global_discount_view.xml",
        'wizard/eran_mrp_non_material_wizard_views.xml',
        'wizard/eran_delivery_schedule_view.xml',
        'wizard/eran_sale_invoice_advance_wiz_view.xml',
        'wizard/eran_purchase_order_advance_payment_wiz_view.xml',

        'views/eran_menu_views.xml', #<<--- letakan selalu paling bawah
    ],
    'depends': ['base', 'account', 'stock', 'purchase', 'sale', 'quality', 'quality_control', 'purchase_request', 'barcodes', 'stock_barcode', 
        'mrp_account_enterprise', 'dsn_approval_purchase', 'dsn_sequence_setting', 'product', 'hr', 'invoice_from_picking', 'mrp',
        'mrp_forecast_order','stock_picking_batch', 'stock_no_negative', 'sale_stock', 'dsn_approval_stock', 'dsn_approval_mrp' ,
        'dsn_approval_sale','dsn_approval_qc','l10n_id_efaktur', 'mrp_workorder', 'report_xlsx', 'purchase_down_payment', 'account_reports','stock_account',
        'hr_attendance'],
    'auto_install': False,
    'installable': True,
    'application': False,
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
           'eran_custom/static/src/**/*',
        ]
    }

}